Feat: 기본 엔티티 추가
ForUs-KW/NaviForYou_Backend pull request #2
Opened 2024-01-17 15:07 UTC by ckdals4600

## 작업사항
- 기본 엔티티 추가
    - User 엔티티
    - Alert 엔티티
    - Building 엔티티
    - Accessibillity 엔티티
    - CustomizedAccessibility 엔티티
    - UserCustomized 엔티티

## 비고
- N+1 문제 고려한 수정 가능성 존재

## Github 이슈
- #1

## 작업일자
- 2024.01.18

<br>

2024-01-17 16:56 UTC, sohyun-99 requested changes
확인했습니다👍 
추가로 다운그레이드 부탁드립니다🙏😢

2024-01-17 16:56 UTC, sohyun-99 commented on src/main/java/forus/naviforyou/global/common/entity/enums/Role.java
> +    ROLE_USER, ROLE_ADMIN, ROLE_CERTIFIED, ROLE_SUSPENDED
ROLE_CERTIFIED, ROLE_SUSPENDED 무슨 역할을 의미하는 건가요??

2024-01-18 02:45 UTC, ckdals4600 commented on src/main/java/forus/naviforyou/global/common/entity/enums/Role.java
> +    ROLE_USER, ROLE_ADMIN, ROLE_CERTIFIED, ROLE_SUSPENDED
ROLE_CERTIFIED는 인증이 완료된 사용자를 의미하고 ROLE_SUSPENDED는 허용되지 사용으로 인해 서비스 사용이 중지된 사용자를 의미합니다!
현재 저희 서비스에는 사용이 되지 않을 거 같은데 나중에 사용할 일이 있을 거 같아 추가해놨습니다.

2024-01-18 02:50 UTC, sohyun-99 approved these changes
확인했습니다 고생하셨어요 💯

2024-01-18 05:02 UTC, merged