Feat: 기존 네이버 지역 API -> 티맵 POI API 변경
ForUs-KW/NaviForYou_Backend pull request #55
Opened 2024-02-10 05:17 UTC by ckdals4600

## 작업사항
- 티맵 API 연결
    - 장소(POI) 통합 검색 API
    - 거리순 검색
    - 명칭(POI) 상세 정보 검색 API
 - 건물 정보 API

## Github 이슈
- #54 

## 작업일자
- 2024.02.10

<br>

2024-02-12 07:56 UTC, sohyun-99 requested changes
고생많으셨습니다ㅜㅜ 꼼꼼히 잘되어있는 것이 느껴지네용! 이제 거의 막바지니까 힘내보아요!! 👍

2024-02-12 07:56 UTC, sohyun-99 commented on src/main/java/forus/naviforyou/domain/place/controller/PlaceController.java
> +    }
이 부분은 swagger 문구를 일부로 빼놓으신 건가요 ??

2024-02-12 07:56 UTC, sohyun-99 commented on src/main/java/forus/naviforyou/domain/place/dto/tmap/PoiBuildingInfo.java
> +
이 함수는 어떤 처리를 담당하는 건가요??

2024-02-12 07:56 UTC, sohyun-99 commented on src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
> +
새로 티맵 api 불러오시느라 고생하셨네요ㅠㅠ

2024-02-12 07:56 UTC, sohyun-99 commented on src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
> +            log.info("e:",e);
저희 코드에 존재하는 log나 system.out 문구는 모두 삭제하여 코드를 정리하는 것이 좋을 듯 합니다.
저도 이런 부분이 존재하는 지 확인 후에 삭제할 예정입니다 !

2024-02-12 07:56 UTC, sohyun-99 commented on src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
> +        BuildingIdDto managementBuildingId = getBuildingIdApi(req.buildingName(), req.roadAddress());
이렇게 바꾸신 이유가 있나요??

2024-02-12 07:56 UTC, sohyun-99 commented on src/main/java/forus/naviforyou/domain/search/dto/request/SearchReq.java
>      private double y;
이 부분은 제가 초기에 작성했던 부분이긴 합니다만, 길찾기에 해당하는 x,y좌표를 모두 string으로 통일했는데 프론트 편의를 위해 이 부분도 string으로 바꾸는 것은 어떨까요??

2024-02-12 07:56 UTC, sohyun-99 commented on src/main/java/forus/naviforyou/domain/search/dto/response/SearchRes.java
깔끔하게 정리되어있네요 ! 👍

2024-02-12 07:56 UTC, sohyun-99 commented on src/main/java/forus/naviforyou/domain/search/service/SearchService.java
잘 수정해주셔서 감사합니다.

2024-02-12 08:44 UTC, ckdals4600 commented on src/main/java/forus/naviforyou/domain/place/controller/PlaceController.java
> +    }
이 부분은 해당 이슈에서는 완성되지 않고 단지 기능만 추가한 부분이였기 때문에 Swagger 문구를 작성하지 않았습니다. 
Swagger 문구는 #56 이슈 에서 추가했습니다.

2024-02-12 08:44 UTC, ckdals4600 commented on src/main/java/forus/naviforyou/domain/place/dto/tmap/PoiBuildingInfo.java
> +
해당 부분은 Json에서 ObjectMapper을 이용한 파싱 과정에서 중첩 Object가 있을 경우 바로 참조가 안되고 해당 Object 형식의 클래스를 하나 더 만들어서 파싱을 진행해야 했었는데, 해당 함수을 이용하면 클래스를 하나 더 만들지 않고 중첩 Object를 파싱할 수 있습니다.

2024-02-12 08:44 UTC, ckdals4600 commented on src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
> +
감사합니다 😢

2024-02-12 08:44 UTC, ckdals4600 commented on src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
> +            log.info("e:",e);
넵 알겠습니다. 해당 부분 전부 삭제 하여 commit 하도록 하겠습니다.

2024-02-12 09:01 UTC, ckdals4600 commented on src/main/java/forus/naviforyou/domain/search/dto/request/SearchReq.java
>      private double y;
프론트 팀을 고려하지 못했네요!! 말씀해주셔서 감사합니다. 수정하도록 하겠습니다!

2024-02-12 09:01 UTC, ckdals4600 commented on src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
> +        BuildingIdDto managementBuildingId = getBuildingIdApi(req.buildingName(), req.roadAddress());
record 자료형을 사용하면서 수정되었습니다!

2024-02-12 18:00 UTC, ckdals4600 commented
해당 이슈의 상위 이슈인 #31 이슈에 수정 사항 반영하였습니다!
[6868140](https://github.com/ForUs-KW/NaviForYou_Backend/pull/56/commits/686814041c023869d23e020c491947445fe14afb)
[1f8af16](https://github.com/ForUs-KW/NaviForYou_Backend/pull/56/commits/1f8af16cdbd7f0ebab2c13feebcf6183a2d016b1)
위 커밋 내용 확인 후 머지 부탁드립니다 ㅎ

2024-02-15 15:50 UTC, sohyun-99 approved these changes
고생하셨습니당

2024-02-15 21:36 UTC, merged